name: Run Automated Tests on all non-main branches

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Run all integration and unit tests
        run: dotnet test tests/Hearty.Tests/Hearty.Tests.csproj
